src/frontend/qt/qtkey.h: add missing <stdint.h> import (#520)
Without the change build fails on weekly `gcc-13` snapshot as:

    frontend/qt/qtkey.h:25:19: error: 'uint32_t' was not declared in this scope
       25 | int keysymToQtKey(uint32_t keysym, const QString &text);
          |                   ^~~~~~~~